apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  labels:
    app: web-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
      protocol: TCP
  selector:
    app: web-api