apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  labels:
    app: configuration
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 8080
      protocol: TCP
  selector:
    app: configuration